### ISSUE TITLE
App stop working with new Beta

### ISSUE THREAD

**Issue by Happyfeet01** [intirix/cloudpasswordmanager#11]
Hello,

with the new Version from the Password Manager the App stop working
v20-beta6 is the latest Version:

![screenshot_20161119-142657](https://cloud.githubusercontent.com/assets/3295104/20455798/02903078-ae65-11e6-81f7-723f3a6a304a.png)

**Comment by intirix** [comment]
The error message is saying that the JSON that the new version is returning is invalid.  I will try installing the v20 beta to see if I can replicate the issue

**Comment by intirix** [comment]
It looks like there are API changes in v20.  I will make changes to support the new version of the API

**Comment by Happyfeet01** [comment]
Thanks

**Comment by intirix** [comment]
It looks like there are two issues.  The first is that there is an API different.  I have resolved that.  The other issue is that there seems to be a problem with the decryption process when you update to v20.  All I can do is better handle decryption failures.  Now, instead of kicking you out, you will see which passwords failed to decrypt.  I am trying to publish the the Alpha channel right now

**Comment by e-alfred** [comment]
Hello,

is this problem fixed? I get the same message v20-beta9 after trying to login.

**Comment by intirix** [comment]
I updated the app to handle the API change for v20 beta6.  I don't have a v20 beta9 environment set up, but I can try to set up one to test against it.  If it is the decryption issue, there is nothing I can do.  Anything using the API would not work.  Did you just upgrade the Passwords app?  What version of OwnCloud are you using?

**Comment by e-alfred** [comment]
I came from an older v20 beta release. I am running Owncloud 9.1.5. The app shows a white screen after logging in for a second and then throwing me back to the login screen with the above error message.

**Comment by intirix** [comment]
It looks like there is an API change.  In previous releases, the REST call to list passwords returned a list of password objects.  Now, the REST call returns a map of passwords, where the unique id of the password is the key.  It will take some time to figure out, because I got threw an abstraction layer to make REST calls and parse the JSON.

**Comment by intirix** [comment]
I pushed a new version to the Play Store that should resolve this issue

**Comment by pafcioooo** [comment]
Works like a charm:-)
